name: CI
on:
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        pwd
        ls -al
    - container:
        image: gableroux/unity3d:2018.4.6f1
      run: |
        ls -al

